"""Convert the (simple) Markdown produced by the UI into a Word document."""

from __future__ import annotations

import io
import re

from docx import Document
from docx.shared import Pt
from docx.text.paragraph import Paragraph

_HEADING = re.compile(r"^(#{1,4})\s+(.*)$")
_BULLET = re.compile(r"^[-*+]\s+(.*)$")
_NUMBERED = re.compile(r"^\d+[.)]\s+(.*)$")
_INLINE = re.compile(r"(\*\*[^*]+\*\*|\*[^*]+\*)")
_TABLE_DIVIDER = re.compile(r"^\|?\s*:?-{3,}")

FOOTER = "Generated by LexiGuide: legal information to help you understand your documents, not legal advice."


def _add_inline(paragraph: Paragraph, text: str) -> None:
    """Add text to ``paragraph`` honouring **bold** and *italic* markers."""
    for part in _INLINE.split(text):
        if not part:
            continue
        if part.startswith("**") and part.endswith("**"):
            paragraph.add_run(part[2:-2]).bold = True
        elif part.startswith("*") and part.endswith("*") and len(part) > 2:
            paragraph.add_run(part[1:-1]).italic = True
        else:
            paragraph.add_run(part)


def _table_cells(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def markdown_to_docx(title: str, markdown: str) -> bytes:
    """Render headings, lists, quotes, tables and paragraphs into a .docx file."""
    document = Document()
    document.core_properties.title = title
    document.styles["Normal"].font.size = Pt(11)
    document.add_heading(title, level=0)

    lines = markdown.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index].strip()
        index += 1
        if not line:
            continue
        if line.startswith("|"):
            rows = [_table_cells(line)]
            while index < len(lines) and lines[index].strip().startswith("|"):
                if not _TABLE_DIVIDER.match(lines[index].strip()):
                    rows.append(_table_cells(lines[index]))
                index += 1
            width = max(len(r) for r in rows)
            table = document.add_table(rows=len(rows), cols=width)
            table.style = "Table Grid"
            for r, row in enumerate(rows):
                for c, cell in enumerate(row):
                    _add_inline(table.cell(r, c).paragraphs[0], cell)
            continue
        if match := _HEADING.match(line):
            document.add_heading(match.group(2), level=min(len(match.group(1)), 3))
        elif match := _BULLET.match(line):
            _add_inline(document.add_paragraph(style="List Bullet"), match.group(1))
        elif match := _NUMBERED.match(line):
            _add_inline(document.add_paragraph(style="List Number"), match.group(1))
        elif line.startswith(">"):
            _add_inline(document.add_paragraph(style="Quote"), line.lstrip("> "))
        else:
            _add_inline(document.add_paragraph(), line)

    footer = document.add_paragraph()
    footer.add_run(FOOTER).italic = True
    buffer = io.BytesIO()
    document.save(buffer)
    return buffer.getvalue()
